---
sidebar: sidebar 
permalink: beegfs-design-solution-sizing-guidelines.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS解决方案 提供了基于验证测试的性能和容量规模估算建议。 
---
= 规模估算准则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BeeGFS解决方案 提供了基于验证测试的性能和容量规模估算建议。

构建块架构的目标是、通过添加多个构建块来满足特定BeeGFS系统的要求、创建一个易于调整大小的解决方案。您可以根据以下准则估算满足环境要求所需的BeeGFS组件的数量和类型。

请记住、这些估计是最佳性能。我们编写并利用了综合基准测试应用程序、以便以实际应用程序可能无法实现的方式优化底层文件系统的使用。



== 性能规模估算

下表提供了建议的性能规模估算。

|===
| 配置配置文件 | 1 MiB读取 | 1 MiB写入 


| 元数据+存储 | 62 GiBps | 21 GiBps 


| 仅存储 | 64 GiBps | 21 GiBps 
|===
元数据容量估算是根据"经验法则"估算的、即500 GB的容量足以容纳BeeGFS中大约1.5亿个文件。(有关详细信息、请参见的BeeGFS文档 https://doc.beegfs.io/latest/system_design/system_requirements.html["系统要求"^]）

使用访问控制列表等功能以及每个目录的目录和文件数量也会影响元数据空间的使用速度。存储容量估计值会考虑可用驱动器容量以及RAID 6和XFS开销。



== 元数据+存储组件的容量规模估算

下表提供了元数据和存储组件的建议容量大小调整。

|===
| 驱动器大小(2+2 RAID 1)元数据卷组 | 元数据容量(文件数) | 驱动器大小(8+2 RAID 6)存储卷组 | 存储容量(文件内容) 


| 1.92 TB | 1、797、120、000 | 1.92 TB | 47.91 TB 


| 3.84 TB | 3、595、240、000 | 3.84 TB | 95.84 TB 


| 7.68 TB | 7、557、120、000 | 7.68 TB | 201.51 TB 


| 15.3 TB | 16、156、800、000 | 15.3 TB | 430.84 TB 
|===

NOTE: 在估算元数据和存储组件的规模时、您可以使用较小的驱动器作为元数据卷组、而不是存储卷组、从而降低成本。



== 仅存储组件的容量规模估算

下表提供了仅存储组件的容量规模估算规则。

|===
| 驱动器大小(10+2 RAID 6)存储卷组 | 存储容量(文件内容) 


| 1.92 TB | 59.89 TB 


| 3.84 TB | 119.80 TB 


| 7.68 TB | 251.89 TB 


| 15.3 TB | 538.55 TB 
|===

NOTE: 除非启用全局文件锁定、否则将管理服务包含在基本(第一个)组件中所带来的性能和容量开销极小。
