---
sidebar: sidebar 
permalink: second-gen/beegfs-solution-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: NetApp解决方案 上的BeeGFS将BeeGFS并行文件系统与NetApp EF600存储系统相结合、打造了一个可靠、可扩展且经济高效的基础架构、可满足苛刻的工作负载要求。 
---
= 解决方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp解决方案 上的BeeGFS将BeeGFS并行文件系统与NetApp EF600存储系统相结合、打造了一个可靠、可扩展且经济高效的基础架构、可满足苛刻的工作负载要求。



== NVA计划

NetApp解决方案 上的BeeGFS是NetApp验证架构(NVA)计划的一部分、该计划为客户提供针对特定工作负载和使用情形的参考配置和规模估算指导。NVA解决方案经过全面测试和设计、可最大限度地降低部署风险并加快上市速度。



== 设计概述

基于NetApp的BeeGFS解决方案是一个可扩展的组件架构、可针对各种要求苛刻的工作负载进行配置。无论是处理多个小文件、管理大量大文件操作、还是混合工作负载、都可以对文件系统进行自定义以满足这些需求。高可用性内置在设计中、采用双层硬件结构、支持在多个硬件层进行独立故障转移、并确保性能稳定一致、即使在部分系统降级期间也是如此。BeeGFS文件系统支持在不同的Linux分发版之间实现高性能和可扩展的环境、并为客户端提供一个易于访问的存储命名空间。要了解更多信息，请访问 link:beegfs-architecture-overview.html["架构概述"]。



== 用例

以下使用情形适用于NetApp解决方案 上的BeeGFS：

* NVIDIA DGX SuperPOD系统采用采用DGX的A100、H100、H200和B200 GPU。
* 人工智能(AI)、包括机器学习(ML)、深度学习(DL)、大规模自然语言处理(NLP)和自然语言理解(NLF)。有关详细信息，请参见 https://www.netapp.com/blog/beefs-for-ai-fact-vs-fiction/["BeeGFS for AI：事实与虚构"^]。
* 高性能计算(HPC)、包括通过MPI (消息传递接口)和其他分布式计算技术加速的应用程序。有关详细信息，请参见 https://www.netapp.com/blog/beegfs-for-ai-ml-dl/["BeeGFS为何超越HPC"^]。
* 应用程序工作负载的特征为：
+
** 读取或写入大于1 GB的文件
** 多个客户端(10、100和1000)读取或写入同一文件


* 多TB或多PB数据集。
* 需要一个存储命名空间的环境、可以优化大小文件的组合。




== 优势

在NetApp上使用BeeGFS的主要优势包括：

* 提供经验证的硬件设计、可实现硬件和软件组件的全面集成、以确保可预测的性能和可靠性。
* 使用Ansible进行部署和管理、以实现规模化的精简性和一致性。
* 使用E系列性能分析器和BeeGFS插件提供监控和可观察性。有关详细信息，请参见 https://www.netapp.com/blog/monitoring-netapp-eseries/["介绍用于监控NetApp E系列解决方案的框架"^]。
* 高可用性采用共享磁盘架构、可提供数据持久性和可用性。
* 支持使用容器和Kubernetes进行现代工作负载管理和流程编排。有关详细信息，请参见 https://www.netapp.com/blog/kubernetes-meet-beegfs/["Kubernetes认识BeeGFS：一个适应未来需求的投资故事"^]。

