---
sidebar: sidebar 
permalink: second-gen/beegfs-design-performance-tuning.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS解决方案 提供了基于验证测试的性能调整建议。 
---
= 性能调整
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS解决方案 提供了基于验证测试的性能调整建议。

虽然BeeGFS可提供合理的即装即用性能、但NetApp已开发出一组建议的调整参数来最大限度地提高性能。这些参数考虑了底层E系列块节点的功能以及在共享磁盘HA架构中运行BeeGFS所需的任何特殊要求。



== 文件节点的性能调整

您可以配置的可用调整参数包括：

. *文件节点的UEFI/BIOS中的系统设置。*为最大限度地提高性能、建议在用作文件节点的服务器型号上配置系统设置。在设置文件节点时、您可以使用由基板管理控制器(BMC)提供的系统设置(UEFI/BIOS)或Redfish API来配置系统设置。
+
系统设置因用作文件节点的服务器型号而异。必须根据所使用的服务器型号手动配置这些设置。要了解如何配置已验证的 Lenovo SR665 V3 文件节点的系统设置，请参阅link:beegfs-deploy-file-node-tuning.html["调整文件节点系统设置以提高性能"] 。

. *所需配置参数的默认设置。*所需配置参数会影响BeeGFS服务的配置方式以及Pacemaker对E系列卷(块设备)进行格式化和挂载的方式。这些必需的配置参数包括：
+
** BeeGFS服务配置参数
+
您可以根据需要覆盖配置参数的默认设置。有关可针对特定工作负载或用例调整的参数，请参见 https://github.com/NetApp/beegfs/blob/master/roles/beegfs_ha_7_4/defaults/main.yml#L237["BeeGFS服务配置参数"^]。

** 卷格式化和挂载参数设置为建议的默认值、只能针对高级使用情形进行调整。默认值将执行以下操作：
+
*** 根据目标类型(例如管理、元数据或存储)以及底层卷的RAID配置和分段大小优化初始卷格式化。
*** 调整Pacemaker挂载每个卷的方式、以确保所做的更改立即刷新到E系列块节点。这样可以防止在文件节点发生故障且正在进行活动写入时丢失数据。
+
有关可针对特定工作负载或用例调整的参数，请参见 https://github.com/NetApp/beegfs/blob/master/roles/beegfs_ha_7_4/defaults/main.yml#L279["卷格式化和挂载配置参数"^]。





. *安装在文件节点上的Linux操作系统中的系统设置。*您可以在的步骤4中创建Ands恢复 清单时覆盖默认的Linux操作系统系统设置 link:beegfs-deploy-create-inventory.html["创建Ansible清单"]。
+
默认设置用于验证NetApp解决方案 上的BeeGFS、但您可以对其进行更改、以便根据您的特定工作负载或使用情形进行调整。您可以更改的Linux操作系统设置示例包括：

+
** E系列块设备上的I/O队列。
+
您可以在用作BeeGFS目标的E系列块设备上配置I/O队列、以便：

+
*** 根据设备类型(NVMe、HDD等)调整计划算法。
*** 增加未处理的请求数。
*** 调整请求大小。
*** 优化预读行为。


** 虚拟内存设置。
+
您可以调整虚拟内存设置、以获得最佳的持续流性能。

** CPU设置。
+
您可以调整CPU频率调速器和其他CPU配置、以获得最高性能。

** 读取请求大小。
+
您可以增加NVIDIA HCA的最大读取请求大小。







== 对块节点进行性能调整

根据应用于特定BeeGFS组件的配置文件、在块节点上配置的卷组会略有变化。例如、对于一个24驱动器EF600块节点：

* 对于单个基础组件、包括BeeGFS管理、元数据和存储服务：
+
** 1个2+2 RAID 10卷组、用于BeeGFS管理和元数据服务
** 2个8+2 RAID 6卷组、用于BeeGFS存储服务


* 对于BeeGFS元数据+存储构建块：
+
** 1个2+2 RAID 10卷组、用于BeeGFS元数据服务
** 2个8+2 RAID 6卷组、用于BeeGFS存储服务


* 仅限BeeGFS存储组件：
+
** 2个10+2 RAID 6卷组、用于BeeGFS存储服务





NOTE: 与存储相比、BeeGFS对管理和元数据所需的存储空间要少得多、因此可以选择为RAID 10卷组使用较小的驱动器。较小的驱动器应填充到最外侧的驱动器插槽中。有关详细信息，请参见 link:beegfs-deploy-overview.html["部署说明"]。

所有这些设置均由基于Ansible的部署进行配置、此外、通常还建议使用其他几种设置来优化性能/行为、其中包括：

* 将全局缓存块大小调整为32 KiB、并将基于需求的缓存刷新调整为80%。
* 禁用自动加载平衡(确保控制器卷分配保持预期状态)。
* 启用读取缓存和禁用预读缓存。
* 通过镜像启用写入缓存并要求使用电池备份、以便在块节点控制器发生故障时保持缓存不变。
* 指定驱动器分配给卷组的顺序、在可用驱动器通道之间平衡I/O。

