---
sidebar: sidebar 
permalink: administer-clusters-expand-shrink-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: 在集群中添加或删除组件。 
---
= 扩展或缩减集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在集群中添加或删除组件。



== 概述

本节介绍了调整BeeGFS HA集群大小的各种注意事项和选项。通常、可以通过添加或删除组件来调整集群大小、这些组件通常是将两个文件节点设置为HA对的组件。如果需要、还可以添加或删除单个文件节点(或其他类型的集群节点)。



== 向集群添加组件



=== 注意事项

通过添加更多组件来扩展集群是一个简单的过程。开始之前、请牢记每个HA集群中集群节点的最小和最大数量限制、并确定是否应向现有HA集群添加节点或创建新的HA集群。通常、每个组件都包含两个文件节点、但每个集群的最小节点数为三个节点(用于建立仲裁)、建议的最大值为十个(已测试)。对于高级情形、可以在部署双节点集群时添加一个不运行任何BeeGFS服务的"Tiebreaker "节点。如果您考虑进行此类部署、请联系NetApp支持部门。

在决定如何扩展集群时、请记住这些限制以及任何预期的未来集群增长。例如、如果您有一个六节点集群、并且需要再添加四个节点、则建议您只启动一个新的HA集群。


TIP: 请记住、一个BeeGFS文件系统可以由多个独立的HA集群组成。这样、文件系统就可以继续扩展、远远超出底层HA集群组件的建议/硬限制。



=== 步骤

向集群添加组件时、您需要创建 `host_vars` 每个新文件节点和块节点(E系列阵列)的文件。需要将这些主机的名称以及要创建的新资源添加到清单中。对应的 `group_vars` 需要为每个新资源创建文件。请参见 link:custom-architectures-overview.html["使用自定义架构"^] 部分以了解详细信息。

创建正确的文件后、只需使用命令重新运行自动化即可：

[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----


== 从集群中删除组件

在需要停用组件时、需要牢记一些注意事项、例如：

* 此组件正在运行哪些BeeGFS服务？
* 是否只是文件节点停用、块节点应附加到新的文件节点？
* 如果停用整个组件、数据应移至新的组件、分散到集群中的现有节点中、还是移动到新的BeeGFS文件系统或其他存储系统？
* 是否可以在中断期间发生这种情况、或者是否应在无中断的情况下进行？
* 该组件是否正在使用中、或者它是否主要包含不再处于活动状态的数据？


由于可能的起始点和所需的最终状态各不相同、因此请联系NetApp支持部门、以便我们能够根据您的环境和要求确定并帮助实施最佳策略。
