---
sidebar: sidebar 
permalink: administer-clusters-overview.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration 
summary: 了解如何在部署BeeGFS HA集群后对其进行管理。 
---
= 概述、关键概念和术语
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解如何在部署BeeGFS HA集群后对其进行管理。



== 概述

本节面向需要在部署BeeGFS HA集群后对其进行管理的集群管理员。即使是熟悉Linux HA集群的用户也应阅读本指南、因为在管理集群方面存在许多差异、尤其是在使用Ansible进行重新配置方面。



== 关键概念

虽然其中一些概念是在主上介绍的 link:beegfs-terms.html["术语和概念"] 页面上、在BeeGFS HA集群的上下文中重新介绍这些配置非常有用：

"*集群节点：*运行Pacemaker和Corosync服务并加入HA集群的服务器。

*文件节点：*用于运行一个或多个BeeGFS管理、元数据或存储服务的集群节点。

"*块节点：*一种为文件节点提供块存储的NetApp E系列存储系统。这些节点不会加入BeeGFS HA集群、因为它们可以提供自己的独立HA功能。每个节点都包含两个存储控制器、这些控制器可在块层提供高可用性。

"BeeGFS服务：* BeeGFS管理、元数据或存储服务。每个文件节点将运行一个或多个服务、这些服务将使用块节点上的卷来存储其数据。

*构建块：* BeeGFS文件节点、E系列块节点以及在其上运行的BeeGFS服务的标准化部署、可简化按照NetApp经验证的架构横向扩展BeeGFS HA集群/文件系统的过程。自定义HA集群也受支持、但通常会采用类似的组件方法来简化扩展。

"BeeGFS HA Cluster"：*用于运行由块节点提供支持的BeeGFS服务以高可用性方式存储BeeGFS数据的文件节点数量可扩展。基于行业认可的开源组件Pacemaker和Corosync构建、并使用Ansible进行打包和部署。

"*集群服务："*是指在加入集群的每个节点上运行的Pacemaker和Corosync服务。请注意、如果只需要两个文件节点、则节点可能不会运行任何BeeGFS服务、而是仅以"Tiebreaker "节点的形式加入集群。

"*集群资源："*对于集群中运行的每个BeeGFS服务、您将看到一个BeeGFS监控资源和一个资源组、其中包含BeeGFS目标、IP地址(浮动IP)和BeeGFS服务本身的资源。

"*可访问：*一种用于软件配置、配置管理和应用程序部署的工具、可将基础架构作为代码来启用。如何打包BeeGFS HA集群、以简化在NetApp上部署、重新配置和更新BeeGFS的过程。

"* pcs："* a command line interface available from any of the file nodes in the cluster used to query and control the state of nodes and resources in the cluster.



== 通用术语

**故障转移：*每个BeeGFS服务都有一个首选文件节点、除非该节点发生故障。当BeeGFS服务在非首选/二级文件节点上运行时、该服务称为处于故障转移状态。

"*。*故障恢复：*将BeeGFS服务从非首选文件节点移回其首选节点的操作。

"HA对："*可以访问同一组块节点的两个文件节点有时也称为HA对。这是整个NetApp通用的一个术语、指可以相互"接管"的两个存储控制器或节点。

"*维护模式："*"会禁用所有资源监控、并阻止Pacemaker移动或以其他方式管理集群中的资源(另请参见上的一节 link:administer-clusters-maintenance-mode.html["维护模式"^]）。

** HA集群：*一个或多个运行BeeGFS服务的文件节点、这些文件节点可以在集群中的多个节点之间进行故障转移、以创建高可用性的BeeGFS文件系统。通常、文件节点会配置为HA对、这些HA对能够在集群中运行一部分BeeGFS服务。
