---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: 使用Ansible更新BeeGFS和HA集群。 
---
= 升级 BeeGFS 服务
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 Ansible 更新 HA 集群上运行的 BeeGFS 版本。



== 概述

BeeGFS采用 `major.minor.patch`版本控制方案。每个受支持的 `major.minor`版本(例如 `beegfs_ha_7_2`和 `beegfs_ha_7_3`)都提供了BeeGFS HA Ansient角色。每个HA角色都固定为在发布此Ansient集合时提供的最新BeeGFS修补程序版本。

所有 BeeGFS 升级都应使用 Ansible，包括在 BeeGFS 的主要、次要和补丁版本之间切换。要更新 BeeGFS，您首先需要更新 BeeGFS Ansible 集合，该集合还将引入部署/管理自动化和底层 HA 集群的最新修复和增强功能。即使更新到最新版本的集合，在运行 `ansible-playbook`并设置 `-e "beegfs_ha_force_upgrade=true"`之前，BeeGFS 也不会升级。有关每次升级的其他详细信息，请参阅当前版本的link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["BeeGFS升级文档"^]。


NOTE: 如果要升级到 BeeGFS 8，请参见link:clusters-upgrade-beegfs-v8.html["升级到 BeeGFS 8"]过程。



== 已测试升级路径

已测试和验证以下升级路径：

[cols="1,1,1,5"]
|===
| 原始版本 | 升级版本 | 多导轨 | 详细信息 


| 7.2.6 | 7.3.2 | 是的。 | 将beegfs收集从v3.0.1升级到v3.1.0、添加了多轨 


| 7.2.6 | 7.2.8 | 否 | 将beegfs收集从v3.0.1升级到v3.1.0 


| 7.2.8 | 7.3.1 | 是的。 | 使用beegfs集合v3.1.0进行升级、并添加了多轨 


| 7.3.1 | 7.3.2 | 是的。 | 使用beegfs Collection v3.1.0进行升级 


| 7.3.2 | 7.4.1 | 是的。 | 使用beegfs Collection v3.2.0进行升级 


| 7.4.1 | 7.4.2 | 是的。 | 使用beegfs Collection v3.2.0进行升级 


| 7.4.2 | 7.4.6 | 是的。 | 使用beegfs Collection v3.2.0进行升级 


| 7.4.6 | 8.0 | 是的。 | 使用link:clusters-upgrade-beegfs-v8.html["升级到 BeeGFS 8"]过程中的说明进行升级。 


| 7.4.6 | 8.1 | 是的。 | 使用link:clusters-upgrade-beegfs-v8.html["升级到 BeeGFS 8"]过程中的说明进行升级。 


| 7.4.6 | 8.2 | 是的。 | 使用link:clusters-upgrade-beegfs-v8.html["升级到 BeeGFS 8"]过程中的说明进行升级。 
|===


== BeeGFS升级步骤

以下各节介绍了更新BeeGFS的Ansient集合和BeeGFS本身的步骤。请特别注意更新BeeGFS主要或次要版本的任何额外步骤。



=== 第1步：升级BeeGFS集合

用于升级可访问的集合 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galax河"^]下，运行以下命令：

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
要进行脱机收集升级、请从下载此收集 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible Galax河"^] 单击所需的 `Install Version`` 然后 `Download tarball`。将tarball传输到Ansible控制节点并运行以下命令。

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
请参见 link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["正在安装收集"^] 有关详细信息 ...



=== 第2步：更新Ands处理 清单

对集群的 Ansible 清单文件进行任何必需的或所需的更新。请参阅以下 <<版本升级说明>> 部分，了解有关特定升级要求的详细信息。有关配置 BeeGFS HA 清单的一般信息，请参阅 link:../custom/architectures-inventory-overview.html["Ansible清单概述"^] 部分。



=== 第3步：更新《Ands维修 手册》(仅在更新主要或次要版本时)

如果要在主要版本或次要版本之间切换、请在用于部署和维护集群的文件中 `playbook.yml` 更新角色名称、 `beegfs_ha_<VERSION>` 以反映所需的版本。例如，如果您要部署BeeGFS 7.4，则该文件为 `beegfs_ha_7_4`：

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
有关此播放手册文件内容的更多详细信息、请参见link:../custom/architectures-deploy-ha-cluster.html["部署BeeGFS HA集群"^]一节。



=== 第4步：运行BeeGFS升级

要应用BeeGFS更新、请执行以下操作：

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
BeeGFS HA角色将在后台处理：

* 确保集群处于最佳状态、每个BeeGFS服务都位于其首选节点上。
* 将集群置于维护模式。
* 更新HA集群组件(如果需要)。
* 按照以下步骤逐个升级每个文件节点：
+
** 将其置于备用状态并将其服务故障转移到二级节点。
** 升级BeeGFS软件包。
** 回退服务。


* 将集群移出维护模式。




== 版本升级说明



=== 从BeeGFS 7.2.6或7.3.0版升级



==== 对基于连接的身份验证进行的更改

BeeGFS 版本 7.3.2 及更高版本要求配置基于连接的身份验证。如果没有以下任何一项，服务将无法启动：

* 指定一个 `connAuthFile`，或
* 在服务的配置文件中设置 `connDisableAuthentication=true`。


强烈建议启用基于连接的身份验证以实现安全。有关更多信息，请参见 link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["基于BeeGFS连接的身份验证"^]。

 `beegfs_ha*` 角色会自动生成身份验证文件并将其分发到：

* 集群中的所有文件节点
* Ansible 控制节点位于 `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`


当此文件存在时，该 `beegfs_client`角色将自动检测并将其应用于客户端。


WARNING: 如果未使用 `beegfs_client`角色配置客户端，则必须向每个客户端手动分发身份验证文件并在 `beegfs-client.conf`文件中配置 `connAuthFile`设置。从没有基于连接的身份验证的 BeeGFS 版本升级时，除非您在升级期间通过在 `group_vars/ha_cluster.yml`中设置 `beegfs_ha_conn_auth_enabled: false`来禁用基于连接的身份验证（不推荐），否则客户端将失去访问权限。

有关其他详细信息和备用配置选项，请参见 link:../custom/architectures-inventory-common-file-node-configuration.html["指定通用文件节点配置"^] 节中的连接身份验证配置步骤。
