---
sidebar: sidebar 
permalink: custom/architectures-inventory-beegfs-metadata.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'BeeGFS服务使用组变量(group_vars)进行配置。' 
---
= 定义BeeGFS元数据服务
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS服务使用组变量(group_vars)进行配置。



== 概述

本节将介绍如何定义BeeGFS元数据服务。对于特定文件系统、HA集群中应至少存在一个此类型的服务。配置此服务包括定义：

* 服务类型(元数据)。
* 定义应仅适用于此BeeGFS服务的任何配置。
* 配置可访问此服务的一个或多个浮动IP (逻辑接口)。
* 指定卷存储此服务数据的位置/方式(BeeGFS元数据目标)。




== 步骤

参考link:architectures-plan-file-system.html["规划文件系统"^]部分、 `group_vars/meta_<ID>.yml`为集群中的每个元数据服务创建一个位于的文件、然后按如下所示填充它们：

. 指示此文件表示BeeGFS元数据服务的配置：
+
[source, yaml]
----
beegfs_service: metadata
----
. 定义应仅应用于此BeeGFS服务的任何配置。您必须至少指定所需的TCP和UDP端口、无论这些端口来自哪个受支持的配置参数 `beegfs-meta.conf` 也可以包括在内。请注意、以下参数是自动/在其他位置配置的、不应在此处指定： `sysMgmtdHost`， `storeMetaDirectory`， `connAuthFile`， `connDisableAuthentication`， `connInterfacesFile`，和 `connNetFilterFile`。
+
[source, yaml]
----
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <TCP PORT>
  connMetaPortUDP: <UDP PORT>
  tuneBindToNumaZone: <NUMA ZONE> # Recommended if using file nodes with multiple CPU sockets.
----
. 配置一个或多个浮动IP、供其他服务和客户端连接到此服务时使用(此操作将自动设置BeeGFS `connInterfacesFile` 选项)：
+
[source, yaml]
----
floating_ips:
  - <INTERFACE>:<IP/SUBNET> # Primary interface. Ex. i1b:100.127.101.1/16
  - <INTERFACE>:<IP/SUBNET> # Secondary interface(s) as needed.
----
. 或者、指定一个或多个允许用于传出通信的IP子网(此操作将自动设置BeeGFS `connNetFilterFile` 选项)：
+
[source, yaml]
----
filter_ip_ranges:
  - <SUBNET>/<MASK> # Ex. 192.168.10.0/24
----
. 根据以下准则指定此服务将在其中存储数据的BeeGFS元数据目标(此操作也会自动配置) `storeMetaDirectory` 选项)：
+
.. 同一存储池或卷组名称可用于多个BeeGFS服务/目标、只需确保使用相同的即可 `name`， `raid_level`， `criteria_*`，和 `common_*` 每个服务的配置(为每个服务列出的卷应不同)。
.. 卷大小应指定为存储池/卷组的百分比、并且使用特定存储池/卷组的所有服务/卷的总数不应超过100。注意使用SSD时、建议在卷组中保留一些可用空间、以最大程度地提高SSD性能和使用寿命(单击可link:../second-gen/beegfs-deploy-recommended-volume-percentages.html["此处"^]了解更多详细信息)。
.. 单击 link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["此处"^] 以获取可用于的配置选项的完整列表 `eseries_storage_pool_configuration`。请注意一些选项、例如 `state`， `host`， `host_type`， `workload_name`，和 `workload_metadata` 和卷名称将自动生成、不应在此指定。




[source, yaml]
----
beegfs_targets:
  <BLOCK_NODE>: # The name of the block node as found in the Ansible inventory. Ex: netapp_01
    eseries_storage_pool_configuration:
      - name: <NAME> # Ex: beegfs_m1_m2_m5_m6
        raid_level: <LEVEL> # One of: raid1, raid5, raid6, raidDiskPool
        criteria_drive_count: <DRIVE COUNT> # Ex. 4
        common_volume_configuration:
          segment_size_kb: <SEGMENT SIZE> # Ex. 128
        volumes:
          - size: <PERCENT> # Percent of the pool or volume group to allocate to this volume. Ex. 1
            owning_controller: <CONTROLLER> # One of: A, B
----
单击 link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/group_vars/meta_01.yml["此处"^] 有关表示BeeGFS元数据服务的完整清单文件的示例。
