---
sidebar: sidebar 
permalink: beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: NetApp解决方案 上的BeeGFS目前正处于第二代设计阶段。 
---
= 设计代数
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp解决方案 上的BeeGFS目前正处于第二代设计阶段。

第一代和第二代均采用一种基础架构、其中整合了BeeGFS文件系统和NVMe EF600存储系统。但是、第二代基于第一代产品构建、其中包括以下附加优势：

* 将性能和容量提高一倍、同时仅添加2U机架空间
* 高可用性(High Availability、HA)基于共享磁盘的两层硬件设计
* NVIDIA DGX A100 SuperPOD和NVIDIA BasePOD架构的外部认证




== 第二代设计

基于NetApp的第二代BeeGFS经过优化、可满足高性能计算(HPC)和HPC模式机器学习(ML)、深度学习(DL)以及类似人工智能(AI)技术等苛刻工作负载的性能要求。通过整合共享磁盘高可用性(HA)架构、NetApp解决方案 上的BeeGFS还可以满足企业和其他组织在寻找可扩展的存储以适应其工作负载和使用情形时无法承受停机或数据丢失的需求。此解决方案 不仅已通过NetApp的验证、还通过了外部认证、作为NVIDIA DGX SuperPOD和DGX BasePOD的存储选项。



== 第一代设计

第一代基于NetApp的BeeGFS专为使用NetApp EF600 NVMe存储系统、BeeGFS并行文件系统、NVIDIA DGX®A100系统和NVIDIA®Mellanox®Quantum®QM8700 200 Gbps IB交换机的机器学习(ML)和人工智能(AI)工作负载而设计。此设计还为存储和计算集群互连网络结构提供了200 Gbps InfiniBand (IB)、可为高性能工作负载提供完全基于IB的架构。

有关第一代产品的详细信息、请参见 link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["采用NVIDIA DGX A100系统和BeeGFS的NetApp EF系列AI"^]。
